# Site settings
title: Matthew Cadier Kim
email: 
description: > # this means to ignore newlines until "baseurl:"
 Graduate student in mathematics interested in combinatorics, discrete geometry, and combinatorial optimization. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://macaki.github.io/" # the base hostname & protocol for your site
twitter_username: 
github_username:  macaki

# Build settings
markdown: kramdown
